HELLO_KERNEL_MODULE_VERSION = 1.0
HELLO_KERNEL_MODULE_SITE = $(TOPDIR)/../hello-kernel-module
HELLO_KERNEL_MODULE_LICENSE = GPL-2.0+
HELLO_KERNEL_MODULE_LICENSE_FILES = COPYING

HELLO_KERNEL_MODULE_BUILD_CMDS = \
    $(MAKE) -C $(LINUX_DIR) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(TARGET_CROSS) M=$(HELLO_KERNEL_MODULE_SITE) modules

HELLO_KERNEL_MODULE_INSTALL_TARGET_CMDS = \
    $(INSTALL) -D -m 644 $(HELLO_KERNEL_MODULE_SITE)/hello.ko $(TARGET_DIR)/lib/modules/$(LINUX_VERSION)/hello.ko

$(eval $(kernel-module))
